### ISSUE TITLE
Can not generate receipt after successful sending request 

### ISSUE THREAD

**Issue by kamal0003** [adityaraval/paytm-integration-nodejs-express#1]
hello, i am facing a problem that after successful sending request to paytm  gateway. It did not generate receipt can you please help me in this

**Comment by adityaraval** [comment]
is there any problem in rendering response.ejs?

**Comment by kamal0003** [comment]
Yes Sir page was not render and {} were shown in webpage

**Comment by adityaraval** [comment]
Inside server.js
on line 37
replace below line
` res.render("response.ejs", {resultData: "true", responseData: success});`
with 
`res.send(success);`

And check what kind of response is being sent by paytm.

**Comment by kamal0003** [comment]
I tried that already.
 Actually i include your code in my main site code and
 include all file path in code

**Comment by kamal0003** [comment]
when i using your code separate it work fine and
 generate receipt but
 when i include in my main code it did not generate  payment receipt

**Comment by adityaraval** [comment]
There must be some small mistake you are doing, just try to debug in each and every steps so you can find issue occurring at exact place.
