### ISSUE TITLE
Cannot POST /paywithpaytm

### ISSUE THREAD

**Issue by gkddev** [adityaraval/paytm-integration-nodejs-express#5]
http://localhost:4000/paywithpaytm?amount=10
 gives error of {Cannot POST /paywithpaytm} and 
when I replaced app.get() to app.all() or app.post() , http://localhost:4000/paywithpaytm?amount=10 does not give error but it seems like moving on a loop ,every 2 second it gets refreshed automatically causing no opening of paytm page..i checked every modules is installed ..and no error in my MID AND KEYS at all.

**Comment by adityaraval** [comment]
It is get request only, can you share your code over email?
So I can help you solve it.

**Comment by gkddev** [comment]
i did not changed anything..code is all the same as i downloaded from your repository..the process environment varriables are all the same as you suggested in readme file and i simply executed your server.js file and error came up.

 Even if you want then 
here is the "server.js" file from your repository
=====================================
const express = require("express");
const bodyParser = require("body-parser");
const cors = require("cors");
const ejs = require("ejs");
const app = express();
require("dotenv").config();

const PORT = process.env.PORT || 4000;

const {initPayment, responsePayment} = require("./paytm/services/index");

app.use(cors());

app.use(bodyParser.json());
app.use(bodyParser.urlencoded({extended: true}));

app.use(express.static(__dirname + "/views"));
app.set("view engine", "ejs");

app.get("/paywithpaytm", (req, res) => {
    initPayment(req.query.amount).then(
        success => {
            res.render("paytmRedirect.ejs", {
                resultData: success,
                paytmFinalUrl: process.env.PAYTM_FINAL_URL
            });
        },
        error => {
            res.send(error);
        }
    );
});

app.post("/paywithpaytmresponse", (req, res) => {
    responsePayment(req.body).then(
        success => {
            res.render("response.ejs", {resultData: "true", responseData: success});
        },
        error => {
            res.send(error);
        }
    );
});

app.listen(PORT, () => {
    console.log("Running on " + PORT);
});
===========================================

here is the  paytm/services/index.js

====================================

const checksum = require('../lib/checksum');
const config = require('../config');
const shortid = require('shortid');

const initPayment = function (amount) {
    return new Promise((resolve, reject) => {
        let paymentObj = {
            ORDER_ID: shortid.generate(),
            CUST_ID: shortid.generate(),
            INDUSTRY_TYPE_ID: config.INDUSTRY_TYPE_ID,
            CHANNEL_ID: config.CHANNEL_ID,
            TXN_AMOUNT: amount.toString(),
            MID: config.MID,
            WEBSITE: config.WEBSITE,
            CALLBACK_URL: config.CALLBACK_URL
        };

        checksum.genchecksum(paymentObj, config.PAYTM_MERCHANT_KEY, (err, result) => {
            if (err) {
                return reject('Error while generating checksum');
            } else
                return resolve(result);
        });
    });
};

const responsePayment = function (paymentObject) {
    return new Promise((resolve, reject) => {
        if (checksum.verifychecksum(paymentObject, config.PAYTM_MERCHANT_KEY)) {
            resolve(paymentObject);
        } else {
            return reject('Error while verifying checksum');
        }
        ;
    });
};


module.exports = {
    initPayment: initPayment,
    responsePayment: responsePayment
}

====================================

as you can see ,i didnot changed anything

**Comment by gkddev** [comment]
please solve my issue

**Comment by AshishGarg1988** [comment]
I got same error how you resolve this

**Comment by renjitharj** [comment]
I'm getting the same error. How to solve this
